### ISSUE TITLE
Cannot execute ezdevice --install

### ISSUE THREAD

**Issue by LilyGO** [geeksville/ezdevice-python#1]
![image](https://user-images.githubusercontent.com/31160602/54509290-0f236780-4984-11e9-8083-6b42151eb3c1.png)

### I installed ezdevice. However, when the command “ezdevice --install K "is executed, the terminal displays ezdevice: command not found.

**Comment by geeksville** [comment]
Hi @LilyGO,

Sorry for the late reply.  Somehow I missed this github notification.  It seems that on some linux installs pip doesn't automatically put its binary directory into the PATH.  If your linux machine is like mine, the binary was installed into:

$HOME/.local/bin/ezdevice

So you should be able to run the following:
```
kevinh@kevin-server:~/development/feeder/backend$ $HOME/.local/bin/ezdevice 
usage: ezdevice [-h] [--install {JR,JL,JM,JO,JG,JK,JY,JC,JT,MB,MS}] [--readee]
                [--target TARGET] [--displayfile DISPLAYFILE] [--claim]
                [--release] [--localserve] [--debug]

optional arguments:
  -h, --help            show this help message and exit
  --install {JR,JL,JM,JO,JG,JK,JY,JC,JT,MB,MS}
                        Install the ezdevice code onto a new device (you must
                        select the board type letter - see README.md)
  --readee              Extract the eeprom contents from the device, so it can
                        be programmed onto other boards
  --target TARGET       The device we are controlling given as ID (secretkey
                        will be added later)
  --displayfile DISPLAYFILE
                        display a text,html,png,svg or jpeg file on the
                        display
  --claim               Mark that this device is no longer being used for
                        custom development
  --release             Mark that this device is no longer being used for
                        custom development (i.e. return to joyframe demo app)
  --localserve          Talk to a development server
  --debug               Show debug log message

```
(or you can add $HOME/.local/bin to your PATH in ~/.bashrc)

Please let me know how it goes and I promise to respond promptly.  I will be hiking (in Yunnan :-) ) most of the next month so my internet acces may be spotty starting next week.  So please try to contact me this week if possible.

You guys make great stuff btw. -Kevin
